"""Gate-driver Miller hold, rev 5 (gen/gdrv.py): the held-off PV devices with the per-device N-MOSFET clamp at the gate-
Kelvin pins, driven by the PV engineer's physical-leg V_DS(t) at the worst corner (sim/pv_design.leg_run: calibrated
VDMOS with the datasheet capacitance curves, the device's own gate resistors). Baseline on the same waveform: the rev-4
PNP follower network (sim/pv_tradeoff.miller_victim_deck). CALCULATED (ngspice), not measured.

Run: .venv/bin/python sim/gdrv_miller.py   -> sim/out/gdrv_miller/result.json + decks in sim/spice/gdrv_*.cir
"""
import json
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import pv_design as pd      # noqa: E402
import pv_tradeoff as tr    # noqa: E402
import pv_devices as _dv    # noqa: E402
tr.dv = getattr(tr, "dv", _dv)

OUT = os.path.join(HERE, "out", "gdrv_miller")
R_DS_CLAMP = 0.08      # ohm, rev 6 clamp FET Nexperia PMV30ENEA: <= 40 mOhm at VGS 4.5 V (p6) x 1.5 hot (board <= 125 C,
                       # RDSon(Tj) figure) + 2 x 10 mOhm layout; gen/gdrv.py drives it at ~8.6 V (VCG = COM + 5.1 V)
L_CLAMP = 2e-9         # H, gate pin -> clamp FET -> local C_VL -> Kelvin pin loop (layout rule: FET at the device pins)


def design(dev, npar):
    """the PV engineer's design point for this device pair (2-level A17, 32 kHz) without the loss/damper tables"""
    des = tr.build_design(pd.FROZEN["cand"], dev, npar, pd.FROZEN["fsw"], pd.FROZEN["ripple"])
    m_on, _ = tr.transient_check(des)
    assert m_on is not None, dev
    des.update(rg_on_mult=m_on, rg_ks=0.5, dec=pd.DEC_CHOICE)
    return des


def nfet_victim_deck(d, npar, wave, tag, rg, a, rks, voff, vth_victim=None, l_clamp=L_CLAMP):
    """held-off devices, rev-5 network: per gate R_off to VEE (OUTL), 10k to the Kelvin pin, and an N-MOSFET (R_DS_CLAMP,
    body diode, L_CLAMP) from the gate pin to a local VEE node = 1 uF on the device's Kelvin pin, 4.7 ohm from VEE. The
    clamp is ON for the whole window (it is enabled before the complementary turn-on: gdrv design_check asserts that)."""
    tw, vw = wave
    deck = os.path.join(tr.SPICE, f"gdrv_{tag}.cir")
    vic = "vic" if vth_victim is not None else "dut"
    pwl = " ".join(f"{x:.4e} {y:.2f}" for x, y in zip(tw[::2], vw[::2]))
    lines = [f"* rev-5 gate network (N-MOSFET clamp per device), V_DS from the PV leg deck. Generated by sim/gdrv_miller.py",
             tr.vdmos_card(vic, dict(d, vth=vth_victim) if vth_victim else d, a), ".model dbody D(Is=1e-12 N=1.5 Rs=0.05)",
             f"Vd dd 0 PWL({pwl})", "Vsense sl 0 0", f"Rksl kl sl {rks / npar}", f"Vel vel kl {voff}"]
    for k in range(npar):
        gx = "gxl0" if k == 0 else f"gl{k}"
        lines += [f"Ml{k} dd {gx} sl {vic}", f"Rgl{k} vel gl{k} {rg}", f"Rc{k} gl{k} cl{k} {R_DS_CLAMP}",
                  f"Lc{k} cl{k} vl{k} {l_clamp}", f"Dc{k} vl{k} gl{k} dbody", f"Cvl{k} vl{k} sl 1u", f"Rvl{k} vel vl{k} 4.7",
                  f"Rgs{k} gl{k} sl 10k"]
    vecs = "v(dd) v(gl0) v(gxl0) i(Vig0) v(vl0) i(Vd)"
    lines += ["Vig0 gl0 gxl0 0", f".save {vecs}", f".tran 0.05n {tw[-1]:.4e} 0 0.05n", "OPTIONS", ".control", "run",
              f"linearize {vecs}", f"wrdata pv_dpt_gdrv_{tag}.dat {vecs}", "quit", ".endc", ".end"]
    t, (vdd, vg, vgx, ig, vl, idd) = tr._run_deck(deck, lines, "gdrv_" + tag)
    return {"pin_pk": float(vg.max()), "die_pk": float((vgx - ig * d["rg_int"]).max()), "i_m_pk": float(-ig.min()),
            "vl_pk": float(vl.max()), "e_vic": float(np.trapezoid(-vdd * idd, t)), "deck": os.path.relpath(deck, HERE)}


def case(role, dev, npar, rails=(-3.5,), mults=(None,), ls=(L_CLAMP,)):
    des = design(dev, npar)
    cal = tr.calibrate(des["d"], des["dev"])
    d = des["d"]
    res = {"dev": dev, "npar": npar, "rg_ext_on_ohm": cal["rg_eff"] * des["rg_on_mult"], "rg_ext_off_ohm": cal["rg_eff"],
           "rg_int": d["rg_int"], "vth_25_min": d.get("vth_min"), "vth_175_min": d["vth_175_min"], "runs": []}
    worst = (tr.V_OVP, des["i_ocp"])
    for m in mults:
        agg = pd.leg_run(des, *worst, f"gdrv_agg_{dev}", wave=True, mult=m)
        w = agg.pop("wave")
        base = tr.miller_victim_deck(d, npar, w, f"gdrv_rev4_{dev}", cal["rg_eff"], cal["a"], des["rg_ks"])
        for v, lc in [(v, lc) for v in rails for lc in ls]:
            new = nfet_victim_deck(d, npar, w, f"vic_{dev}_{-v:g}_{lc * 1e9:g}", cal["rg_eff"], cal["a"], des["rg_ks"], v,
                                   l_clamp=lc)
            vmin = nfet_victim_deck(d, npar, w, f"vicmin_{dev}_{-v:g}_{lc * 1e9:g}", cal["rg_eff"], cal["a"], des["rg_ks"],
                                    v, d["vth_175_min"], l_clamp=lc)
            res["runs"].append({"rg_on_mult": m or des["rg_on_mult"], "rg_on_ohm": cal["rg_eff"] * (m or des["rg_on_mult"]),
                                "dvdt_on": agg["dvdt_on"] / 1e9, "l_clamp_nH": lc * 1e9, "e_on_J": agg.get("e_on"), "v_pk": agg["v_pk"], "voff": v,
                                "rev4": {"pin": base["vgs_off_peak"], "die": base["vgs_off_peak_die"],
                                         "i_m": base["i_miller_pk"]},
                                "nfet": new, "nfet_vthmin_e_extra_J": vmin["e_vic"] - new["e_vic"]})
            r = res["runs"][-1]
            print(f"{role} {npar} x {dev} Rg,on x{r['rg_on_mult']:.2f} ({r['rg_on_ohm']:.2f} ohm) dv/dt {r['dvdt_on']:.0f} V/ns"
                  f" E_on {1e6 * (r['e_on_J'] or 0):.0f} uJ | rev4 pin {r['rev4']['pin']:+.2f} die {r['rev4']['die']:+.2f} | "
                  f"N-FET @{v:g} V L {lc * 1e9:g} nH pin {new['pin_pk']:+.2f} die {new['die_pk']:+.2f} (I_M {new['i_m_pk']:.2f} A) vs "
                  f"Vth,min,175 {d['vth_175_min']:.2f} V | extra E at Vth,min {1e6 * r['nfet_vthmin_e_extra_J']:.1f} uJ",
                  flush=True)
    return res


def dab_case(role, dev, npar, d_over=None, vdc=950.0, currents=(20.0, 100.0), lloop=15e-9, voff=-3.5, lc=1e-9, rg=None,
             rg_on=None):
    """DAB hard-switched turn-on (light load / fault) at vdc: lumped-loop commutation deck (tr.dpt, low-side DUT turns
    on, the high-side set is the victim); the victim's V_DS(t) then drives the rev-5/6 clamp network as above."""
    d = dict(tr.dv.MOSFETS[dev] if d_over is None else d_over)
    a = tr.fit_vdmos(d, role)[0]
    rg = rg if rg is not None else tr.calibrate(d, dev)["rg_eff"]
    out = {"dev": role, "npar": npar, "vdc": vdc, "rg_ext": rg, "vth_175_min": d["vth_175_min"], "runs": []}
    for i in currents:
        agg = tr.dpt(d, npar, vdc, i, lloop, f"gdrv_dab_{role}_{i:g}", rg=rg, a=a, rg_on=rg_on or rg, vgs_off=voff, rks=0.5,
                     wave=True)
        w = agg.pop("wave")
        new = nfet_victim_deck(d, npar, w, f"dab_{role}_{i:g}", rg, a, 0.5, voff, l_clamp=lc)
        vmin = nfet_victim_deck(d, npar, w, f"dabmin_{role}_{i:g}", rg, a, 0.5, voff, d["vth_175_min"], l_clamp=lc)
        out["runs"].append({"i": i, "rg_on": rg_on or rg, "e_on_J": agg.get("e_on"), "dvdt": agg["dvdt_on"] / 1e9, "die": new["die_pk"], "pin": new["pin_pk"], "i_m": new["i_m_pk"],
                            "e_extra_J": vmin["e_vic"] - new["e_vic"]})
        r = out["runs"][-1]
        print(f"DAB {npar} x {role} {vdc:.0f} V {i:g} A, Rg,on {rg_on or rg:.2f} ohm: E_on {1e6 * (agg.get('e_on') or 0):.0f} uJ, dv/dt {r['dvdt']:.0f} V/ns, die {r['die']:+.2f} V (pin "
              f"{r['pin']:+.2f}, I_M {r['i_m']:.2f} A) vs Vth,min,175 {d['vth_175_min']:.2f} V, extra E {r['e_extra_J'] * 1e6:.1f} uJ",
              flush=True)
    return out


if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    which = sys.argv[1:] or ["primary", "alternate", "alt2"]
    sets = {"primary": ("SG2M040170HJ", 2, (-3.5,), (None,), (0.0, 1e-9, 2e-9)),
            "alternate": ("IV2Q17020T4Z", 2, (-3.5, -5.0), (None, 2.0), (0.0, 1e-9)),
            "alt2": ("IV2Q17040T4Z", 2, (-3.5,), (None,), (0.0, 1e-9)),
            "sc20x1": ("SG2M020170HJ", 1, (-3.5,), (None,), (0.0, 1e-9))}
    out = {}
    for role in which:
        dev, npar, rails, mults, ls = sets[role]
        out[role] = case(role, dev, npar, rails, mults, ls)
    json.dump(out, open(os.path.join(OUT, "result_%s.json" % "_".join(which)), "w"), indent=1)
